heat_template_version: 2021-04-16
parameters:
  clustername:
    type: string
    label: Cluster Name
    description: The name to give the cluster

  external-network:
    type: string
    label: External Network Name
    description: The name of the external network to bridge network to
    default: 'external'

  network-cidr-pri:
    type: string
    label: Primary Nework CIDR
    description: Network CIDR to be used for primary network
    default: '10.10.0.0/16'

  ssh-key:
    type: string
    label: SSH Key for Access (default openflight shared)
    default: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIArVAIt9S9RnY4atvMh5jQOg9X+Iv+uM1yQNuh2k9fXM openflight_shared'

  image:
    type: string
    label: Image ID (default rocky 9.4)
    default: 'd6ccf235-d285-48de-ae86-eb1b261370cc'

  login-flavour:
    type: string
    label: Gateway node flavour
    default: 'm1.medium'

  node-flavour:
    type: string
    label: Node flavour
    default: 'm1.medium'

resources:
  external-route:
    type: OS::Neutron::Router
    depends_on: cluster-network-pri
    properties:
      name: { list_join: ['-', [ {get_param: clustername}, 'ext-route']] }
      external_gateway_info:
        network: { get_param: external-network }

  external-route-iface:
    type: OS::Neutron::RouterInterface
    properties:
      router: { get_resource: external-route }
      subnet: { get_resource: cluster-network-pri }

  cluster-network:
    type: OS::Neutron::Net
    properties:
      name: { list_join: ['-', [{ get_param: clustername }, 'network']] }

  cluster-network-pri:
    type: OS::Neutron::Subnet
    properties:
      name: { list_join: ['-', [ {get_param: clustername}, 'network-pri']] }
      network: { get_resource: cluster-network }
      cidr: { get_param: network-cidr-pri }
      ip_version: 4

  cluster-sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: { list_join: ['-', [ {get_param: clustername}, 'network-pri-sg']] }
      rules:
        - direction: egress
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          remote_ip_prefix: { get_param: network-cidr-pri }
        - direction: ingress
          protocol: icmp
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          port_range_min: 22
          port_range_max: 22
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          port_range_min: 80
          port_range_max: 80
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          port_range_min: 443
          port_range_max: 443
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          port_range_min: 5901
          port_range_max: 5911
          protocol: tcp
          remote_ip_prefix: 0.0.0.0/0
        - direction: ingress
          remote_ip_prefix: { get_param: network-cidr-pri }

  login-pri-port:
    type: OS::Neutron::Port
    depends_on: cluster-network-pri
    properties:
      name: { list_join: ['-', ['login1', 'pri', { get_param: clustername }]] }
      network: { get_resource: cluster-network }
      security_groups:
        - { get_resource: cluster-sg }
      fixed_ips:
        - subnet: { get_resource: cluster-network-pri }
          ip_address: 10.10.0.101

  login-node:
    type: OS::Nova::Server
    properties:
      name: { list_join: ['.', ['login1', { get_param: clustername }, 'cluster.network']] }
      flavor: { get_param: login-flavour }
      admin_user: rocky
      networks:
          - port: { get_resource: login-pri-port }
      block_device_mapping_v2:
        - volume_id: { get_resource: login-vol }
          boot_index: 0
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            fqdn: login1.$clustername.alces.network
            users:
              - default
              - name: rocky
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh-authorized-keys:
                  - $key
            write_files: 
              - content: |
                  # Disable SELinux
                  setenforce 0
                  sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config

                  # Setup /etc/hosts
                  echo "10.10.0.101    login1.$clustername.cluster.network" >> /etc/hosts
                  echo "10.10.1.1      node01.$clustername.cluster.network" >> /etc/hosts
                  echo "10.10.1.2      node02.$clustername.cluster.network" >> /etc/hosts

                  # Setup NFS exports
                  dnf -y install nfs-utils
                  mkdir /data
                  chmod 0755 /data
                  echo "/data    *(rw,no_root_squash)" >> /etc/exports
                  echo "/home    *(rw,no_root_squash)" >> /etc/exports
                  exportfs -a
                  systemctl enable nfs-server --now
                path: /root/setup.sh
                permissions: '0600'
                owner: root:root
            runcmd: 
              - bash /root/setup.sh >> /root/setup.log
          params:
            $key: { get_param: ssh-key }
            $clustername: { get_param: clustername }

  login-vol:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: image }
      size: 32

  login-ip:
     type: "OS::Neutron::FloatingIP"
     properties:
        floating_network_id: {get_param: external-network}
        port_id: {get_resource: login-pri-port}

  node1-pri-port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ['-', ['node01', 'pri', { get_param: clustername }]] }
      network: { get_resource: cluster-network }
      security_groups:
        - { get_resource: cluster-sg }
      fixed_ips:
        - subnet: { get_resource: cluster-network-pri }
          ip_address: 10.10.1.1

  node1:
    type: OS::Nova::Server
    properties:
      name: { list_join: ['.', ['node01', { get_param: clustername }, 'cluster.network']] }
      flavor: { get_param: node-flavour }
      admin_user: rocky
      networks:
          - port: { get_resource: node1-pri-port }
      block_device_mapping_v2:
        - volume_id: { get_resource: node1-vol }
          boot_index: 0
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            fqdn: node01.$clustername.alces.network
            users:
              - default
              - name: rocky
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh-authorized-keys:
                  - $key
            write_files: 
              - content: |
                  # Disable SELinux
                  setenforce 0
                  sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config

                  # Setup /etc/hosts
                  echo "10.10.0.101    login1.$clustername.cluster.network" >> /etc/hosts
                  echo "10.10.1.1      node01.$clustername.cluster.network" >> /etc/hosts
                  echo "10.10.1.2      node02.$clustername.cluster.network" >> /etc/hosts

                  # Setup NFS exports
                  dnf -y install nfs-utils
                  mkdir /data
                  chmod 0755 /data
                  echo "login1.$clustername.cluster.network:/data    /data    nfs    intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail    0 0" >> /etc/fstab
                  echo "login1.$clustername.cluster.network:/home    /home    nfs    intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail    0 0" >> /etc/fstab

                  until [[ $(showmount --no-headers -e login1.$clustername.cluster.network |wc -l) -gt 0 ]]; do
                      # wait for exports to be avail
                      sleep 5
                  done
                  mount -a
                path: /root/setup.sh
                permissions: '0600'
                owner: root:root
            runcmd: 
              - bash /root/setup.sh >> /root/setup.log
          params:
            $key: { get_param: ssh-key }
            $clustername: { get_param: clustername }

  node1-vol:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: image }
      size: 16

  node2-pri-port:
    type: OS::Neutron::Port
    properties:
      name: { list_join: ['-', ['node02', 'pri', { get_param: clustername }]] }
      network: { get_resource: cluster-network }
      security_groups:
        - { get_resource: cluster-sg }
      fixed_ips:
        - subnet: { get_resource: cluster-network-pri }
          ip_address: 10.10.1.2

  node2:
    type: OS::Nova::Server
    properties:
      name: { list_join: ['.', ['node02', { get_param: clustername }, 'cluster.network']] }
      flavor: { get_param: node-flavour }
      admin_user: rocky
      networks:
          - port: { get_resource: node2-pri-port }
      block_device_mapping_v2:
        - volume_id: { get_resource: node2-vol }
          boot_index: 0
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            fqdn: node02.$clustername.alces.network
            users:
              - default
              - name: rocky
                sudo: ALL=(ALL) NOPASSWD:ALL
                ssh-authorized-keys:
                  - $key
            write_files: 
              - content: |
                  # Disable SELinux
                  setenforce 0
                  sed -i 's/^SELINUX=.*/SELINUX=disabled/g' /etc/selinux/config

                  # Setup /etc/hosts
                  echo "10.10.0.101    login1.$clustername.cluster.network" >> /etc/hosts
                  echo "10.10.1.1      node01.$clustername.cluster.network" >> /etc/hosts
                  echo "10.10.1.2      node02.$clustername.cluster.network" >> /etc/hosts

                  # Setup NFS exports
                  dnf -y install nfs-utils
                  mkdir /data
                  chmod 0755 /data
                  echo "login1.$clustername.cluster.network:/data    /data    nfs    intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail    0 0" >> /etc/fstab
                  echo "login1.$clustername.cluster.network:/home    /home    nfs    intr,rsize=32768,wsize=32768,vers=3,_netdev,nofail    0 0" >> /etc/fstab

                  until [[ $(showmount --no-headers -e login1.$clustername.cluster.network |wc -l) -gt 0 ]]; do
                      # wait for exports to be avail
                      sleep 5
                  done
                  mount -a
                path: /root/setup.sh
                permissions: '0600'
                owner: root:root
            runcmd: 
              - bash /root/setup.sh >> /root/setup.log
          params:
            $key: { get_param: ssh-key }
            $clustername: { get_param: clustername }

  node2-vol:
    type: OS::Cinder::Volume
    properties:
      image: { get_param: image }
      size: 16
